CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  full_name VARCHAR(150) NOT NULL,
  email VARCHAR(200) NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS user_sessions (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  session_token VARCHAR(128) NOT NULL UNIQUE,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS pending_user_registrations (
  id SERIAL PRIMARY KEY,
  full_name VARCHAR(150) NOT NULL,
  email VARCHAR(200) NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  otp_code VARCHAR(6) NOT NULL,
  otp_expires_at TIMESTAMPTZ NOT NULL,
  verified_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS devices (
  id SERIAL PRIMARY KEY,
  device_id VARCHAR(100) NOT NULL UNIQUE,
  device_name VARCHAR(150) NOT NULL,
  device_type VARCHAR(100) NOT NULL DEFAULT 'arduino',
  board_model VARCHAR(150),
  fqbn VARCHAR(200),
  serial_number VARCHAR(150),
  location VARCHAR(150),
  wifi_ssid VARCHAR(150),
  wifi_password TEXT,
  wifi_configured_at TIMESTAMPTZ,
  device_secret VARCHAR(128),
  last_seen_at TIMESTAMPTZ,
  last_status VARCHAR(30),
  led_state VARCHAR(10) NOT NULL DEFAULT 'OFF',
  thing_variables JSONB NOT NULL DEFAULT '[]'::jsonb,
  owner_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS led_commands (
  id SERIAL PRIMARY KEY,
  device_id VARCHAR(100) NOT NULL REFERENCES devices(device_id) ON DELETE CASCADE,
  command VARCHAR(10) NOT NULL,
  source VARCHAR(50) NOT NULL DEFAULT 'next-app',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS things (
  id SERIAL PRIMARY KEY,
  device_id VARCHAR(100) NOT NULL REFERENCES devices(device_id) ON DELETE CASCADE,
  owner_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  thing_name VARCHAR(150) NOT NULL,
  device_sketch VARCHAR(200) NOT NULL DEFAULT 'uno_r4_wifi_cloud_device',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (device_id)
);

CREATE TABLE IF NOT EXISTS thing_variables (
  id SERIAL PRIMARY KEY,
  thing_id INTEGER NOT NULL REFERENCES things(id) ON DELETE CASCADE,
  variable_name VARCHAR(150) NOT NULL,
  variable_type VARCHAR(40) NOT NULL DEFAULT 'boolean',
  permission VARCHAR(40) NOT NULL DEFAULT 'read_write',
  declaration VARCHAR(150) NOT NULL,
  update_policy VARCHAR(40) NOT NULL DEFAULT 'on_change',
  sync_enabled BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (thing_id, variable_name)
);

CREATE TABLE IF NOT EXISTS dashboards (
  id SERIAL PRIMARY KEY,
  owner_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  dashboard_name VARCHAR(150) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS dashboard_tiles (
  id SERIAL PRIMARY KEY,
  dashboard_id INTEGER NOT NULL REFERENCES dashboards(id) ON DELETE CASCADE,
  tile_name VARCHAR(150) NOT NULL,
  tile_type VARCHAR(40) NOT NULL,
  linked_thing_id INTEGER REFERENCES things(id) ON DELETE SET NULL,
  linked_variable_id INTEGER REFERENCES thing_variables(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE devices
ADD COLUMN IF NOT EXISTS owner_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL;

ALTER TABLE devices
ADD COLUMN IF NOT EXISTS device_secret VARCHAR(128);

ALTER TABLE devices
ADD COLUMN IF NOT EXISTS last_seen_at TIMESTAMPTZ;

ALTER TABLE devices
ADD COLUMN IF NOT EXISTS last_status VARCHAR(30);

ALTER TABLE devices
ADD COLUMN IF NOT EXISTS wifi_ssid VARCHAR(150);

ALTER TABLE devices
ADD COLUMN IF NOT EXISTS wifi_password TEXT;

ALTER TABLE devices
ADD COLUMN IF NOT EXISTS wifi_configured_at TIMESTAMPTZ;

ALTER TABLE devices
ADD COLUMN IF NOT EXISTS board_model VARCHAR(150);

ALTER TABLE devices
ADD COLUMN IF NOT EXISTS fqbn VARCHAR(200);

ALTER TABLE devices
ADD COLUMN IF NOT EXISTS serial_number VARCHAR(150);

ALTER TABLE devices
ADD COLUMN IF NOT EXISTS led_state VARCHAR(10) NOT NULL DEFAULT 'OFF';

ALTER TABLE devices
ADD COLUMN IF NOT EXISTS thing_variables JSONB NOT NULL DEFAULT '[]'::jsonb;

ALTER TABLE things
ADD COLUMN IF NOT EXISTS device_sketch VARCHAR(200) NOT NULL DEFAULT 'uno_r4_wifi_cloud_device';

ALTER TABLE things
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

ALTER TABLE thing_variables
ADD COLUMN IF NOT EXISTS declaration VARCHAR(150) NOT NULL DEFAULT '';

ALTER TABLE thing_variables
ADD COLUMN IF NOT EXISTS update_policy VARCHAR(40) NOT NULL DEFAULT 'on_change';

ALTER TABLE thing_variables
ADD COLUMN IF NOT EXISTS sync_enabled BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE thing_variables
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

ALTER TABLE dashboards
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

ALTER TABLE dashboard_tiles
ADD COLUMN IF NOT EXISTS linked_thing_id INTEGER REFERENCES things(id) ON DELETE SET NULL;

ALTER TABLE dashboard_tiles
ADD COLUMN IF NOT EXISTS linked_variable_id INTEGER REFERENCES thing_variables(id) ON DELETE SET NULL;

ALTER TABLE dashboard_tiles
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

ALTER TABLE pending_user_registrations
ADD COLUMN IF NOT EXISTS verified_at TIMESTAMPTZ;

INSERT INTO devices (device_id, device_name, device_type, location)
VALUES ('arduino-led-01', 'Starter LED Device', 'arduino', 'Workbench')
ON CONFLICT (device_id) DO NOTHING;
